### ISSUE TITLE
androidx compatibility issue

### ISSUE THREAD

**Issue by NerdHamel** [marcherdiego/android_mvp#2]
Whenever I try to migrate my project to androidX i Keep getting these errors related to JVM signature clashes for method declarations

I am extending BaseFragment into my NHCFragmentBase     

Inherited platform declarations clash: The following declarations have the same JVM signature (onOptionsItemSelected(Landroid/view/MenuItem;)Z):     fun onOptionsItemSelected(p0: MenuItem): Boolean defined in nhc.onlineshop.baseclasses.NHCFragmentBase     fun onOptionsItemSelected(item: MenuItem?): Boolean defined in nhc.onlineshop.baseclasses.NHCFragmentBase |  
-- | --

Inherited platform declarations clash: The following declarations have the same JVM signature (onConfigurationChanged(Landroid/content/res/Configuration;)V):     fun onConfigurationChanged(p0: Configuration): Unit defined in nhc.onlineshop.baseclasses.NHCFragmentBase     fun onConfigurationChanged(newConfig: Configuration?): Unit defined in nhc.onlineshop.baseclasses.NHCFragmentBase |  
-- | --

Inherited platform declarations clash: The following declarations have the same JVM signature (onCreateOptionsMenu(Landroid/view/Menu;Landroid/view/MenuInflater;)V):     fun onCreateOptionsMenu(p0: Menu, p1: MenuInflater): Unit defined in nhc.onlineshop.baseclasses.NHCFragmentBase     fun onCreateOptionsMenu(menu: Menu?, inflater: MenuInflater?): Unit defined in nhc.onlineshop.baseclasses.NHCFragmentBase |  
-- | --

**Comment by marcherdiego** [comment]
Try removing the `nullable` modifier in the function signatures. Also try updating to the newest version, I can't remember which version was released by the time you filed this issue.
